#!/usr/bin/python
import sys

def pretty_size(size, format='%.1f'):
    if size is None:
        return ''

    jump = 1024
    if size < jump:
        return '%s bytes' % size

    units = ['KB', 'MB', 'GB', 'TB']
    i = 0
    while size >= jump and i < len(units):
        i += 1
        size /= 1024.

    return (format + ' %s') % (size, units[i - 1])


if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit(1)
    print pretty_size(int(sys.argv[1]))
